### ISSUE TITLE
Images Carousel: The hover effect time duration needs to be reduced

### ISSUE THREAD

**Issue by Naresh-kumar-Thodupunoori** [sailingsam/house_arena_react-vite#9]
## Description:
 Currently when we hover over the sliding images they take a huge time to stop sliding which needs to be reduced in first feel it feels like it isn't going to stop so it's important to reduce the time taken to stop that.

**Mainly the user experience currently isn't good for the sliding image's section which need to be fixed.**

## Screen recording ->
[Screencast from 2024-08-06 20-04-26.webm](https://github.com/user-attachments/assets/55f5e457-5433-483e-b71f-f471bb226230)

**Comment by sailingsam** [comment]
issue is related to the implementation of slick-carousel dependency (inside EventsCarousel.JSX file) you will find implementation for this, try searching about this dependency functions or features

**Comment by Naresh-kumar-Thodupunoori** [comment]
@sailingsam I would like to work on it!

**Comment by sailingsam** [comment]
assigned
